version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitoring
    ports:
      - "3306:3306"
    restart: always
